//-----LocalHost-----
//Home
###
GET http://localhost:3000/

//All Animals
###
GET http://localhost:3000/animals/

//Single Animals
###
GET http://localhost:3000/animals/67a4df40f0863b195131b096
###
GET http://localhost:3000/animals/67a4e0b7f0863b195131b097
###
GET http://localhost:3000/animals/67a4e111f0863b195131b099
###
GET http://localhost:3000/animals/67a4e16bf0863b195131b09b
###
GET http://localhost:3000/animals/67a4e210f0863b195131b09f
###
GET http://localhost:3000/animals/1234

//Create
### 
POST http://localhost:3000/animals HTTP/1.1
content-type: application/json

{
    "name": "Bobby",
    "species": "Dog",
    "breed": "Chihuahua",
    "age": 2,
    "constitution": "Bouncy",
    "gender": "M"
}

//Update
### 
PUT http://localhost:3000/animals/67af7f1416c0712c7503e137 HTTP/1.1
content-type: application/json

{
    "name": "Bobby",
    "species": "Dog",
    "breed": "Chihuahua",
    "age": 12,
    "constitution": "Bouncy",
    "gender": "M"
}

//Delete
### 
DELETE http://localhost:3000/animals/67af7f1416c0712c7503e137 HTTP/1.1

//Authorization
###
GET http://localhost:3000/auth/google
###
GET http://localhost:3000/auth/logout

//Employee
//Get One
###
GET http://localhost:3000/employees/id

//Get All
###
GET http://localhost:3000/employees/

//Create
###
POST http://localhost:3000/employees/ HTTP/1.1
content-type: application/json

{
    "name": "Samuel Dobson",
    "age": 57,
    "gender": "M",
    "position": "Night Manager"
}

//Update
###
PUT http://localhost:3000/employees/id HTTP/1.1
content-type: application/json
{
    
}

//Delete
DELETE http://localhost:3000/employees/id HTTP/1.1


//-----Render-----
//All Animals
###
GET https://animalshelter-wyak.onrender.com/animals/

//Single animals
###
GET https://animalshelter-wyak.onrender.com/animals/67a4df40f0863b195131b096
###
GET https://animalshelter-wyak.onrender.com/animals/67a4e0b7f0863b195131b097
###
GET https://animalshelter-wyak.onrender.com/animals/67a4e111f0863b195131b099
###
GET https://animalshelter-wyak.onrender.com/animals/67a4e16bf0863b195131b09b
###
GET https://animalshelter-wyak.onrender.com/animals/67a4e210f0863b195131b09f
###
GET https://animalshelter-wyak.onrender.com/animals/1234 

//Create
### 
POST https://animalshelter-wyak.onrender.com/animals HTTP/1.1
content-type: application/json

{
    "name": "Florence",
    "species": "rat",
    "breed": "Naked Mole",
    "age": 3,
    "constitution": "stealthy",
    "gender": "F"
}

//Update
### 
PUT https://animalshelter-wyak.onrender.com/animals/67af7fea92dd9e2004cb8357 HTTP/1.1
content-type: application/json

{
    "name": "Florence",
    "species": "cat",
    "breed": "Siamese",
    "age": 3,
    "constitution": "stealthy",
    "gender": "M"
}

//Delete
### 
DELETE https://animalshelter-wyak.onrender.com/animals/67af7fea92dd9e2004cb8357 HTTP/1.1



//API Docs
http://localhost:3000/api-docs
https://animalshelter-wyak.onrender.com/api-docs